import mobase
from PyQt6.QtWidgets import QMessageBox
from PyQt6.QtGui import QIcon
from pathlib import Path
import configparser


class RootBuilderConfigurator(mobase.IPluginTool):
    def __init__(self):
        super().__init__()
        self._organiser = None

    def init(self, organiser: mobase.IOrganizer) -> bool:
        self._organiser = organiser
        return True

    def name(self) -> str:
        return "RootBuilderConfigurator"
        
    def author(self) -> str:
        return "d&h"   

    def version(self) -> mobase.VersionInfo:
        if hasattr(mobase, "VersionInfo") and hasattr(mobase, "ReleaseType"):
            return mobase.VersionInfo(1, 0, 0, mobase.ReleaseType.FINAL)
        else:
            print("Error: mobase.VersionInfo or mobase.ReleaseType not available.")
            return None    

    def displayName(self) -> str:
        return "Root Builder Configurator for Bannerlord"

    def description(self) -> str:
        return "Configures Root Builder settings for Bannerlord in ModOrganizer.ini."

    def icon(self):
        return QIcon()  # Replace with QIcon("path/to/icon.png") if you have an icon

    def isActive(self) -> bool:
        return True

    def tooltip(self) -> str:
        return "Configure Root Builder exclusions and priorities for Bannerlord."

    def settings(self):
        return []

    def display(self):
        ini_path = Path(self._organiser.basePath()) / "ModOrganizer.ini"
        config = configparser.ConfigParser(strict=False, delimiters=("=",))
        config.optionxform = str  # Preserve case sensitivity
        config.read(ini_path, encoding="utf-8")

        # Ensure [Plugins] section exists
        if "Plugins" not in config:
            config["Plugins"] = {}

        # Define Root Builder settings
        values = {
            "RootBuilder\\copyfiles": "**",
            "RootBuilder\\linkfiles": "",
            "RootBuilder\\usvfsfiles": "",
            "RootBuilder\\exclusions": '"Data,DigitalCompanion,GUI,Icons,modding_resources,Modules,music,Shaders,Sounds,XmlSchemas,bin\\\\CrashUploader.Publish,bin\\\\Win64_Shipping_wEditor,bin\\\\Win64_Shipping_Client\\\\Microsoft.AspNetCore.App,bin\\\\Win64_Shipping_Client\\\\Microsoft.NETCore.App,bin\\\\Win64_Shipping_Client\\\\Microsoft.WindowsDesktop.App,bin\\\\Win64_Shipping_Client\\\\mono,bin\\\\Win64_Shipping_Client\\\\Watchdog,bin\\\\Win64_Shipping_Client\\\\PhysXGpu_64.dll,bin\\\\Win64_Shipping_Client\\\\EOSSDK.dll,bin\\\\Win64_Shipping_Client\\\\Galaxy64.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Native.dll,bin\\\\Win64_Shipping_Client\\\\nvngx_dlss.dll,bin\\\\Win64_Shipping_Client\\\\mono-2.0-sgen.dll,bin\\\\Win64_Shipping_Client\\\\d3dcompiler_47.dll,bin\\\\Win64_Shipping_Client\\\\GfeSDK.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.dll,bin\\\\Win64_Shipping_Client\\\\PhysX_64.dll,bin\\\\Win64_Shipping_Client\\\\dbghelp.dll,bin\\\\Win64_Shipping_Client\\\\GalaxyCSharpGlue.dll,bin\\\\Win64_Shipping_Client\\\\PhysXCommon_64.dll,bin\\\\Win64_Shipping_Client\\\\msdia140.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.CampaignSystem.ViewModelCollection.dll,bin\\\\Win64_Shipping_Client\\\\GFSDK_Aftermath_Lib.x64.dll,bin\\\\Win64_Shipping_Client\\\\Epic.OnlineServices.dll,bin\\\\Win64_Shipping_Client\\\\grGraniteQuartzFast.dll,bin\\\\Win64_Shipping_Client\\\\PhysXDevice64.dll,bin\\\\Win64_Shipping_Client\\\\Newtonsoft.Json.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Engine.AutoGenerated.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.ViewModelCollection.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Core.dll,bin\\\\Win64_Shipping_Client\\\\GalaxyCSharp.dll,bin\\\\Win64_Shipping_Client\\\\grGranite.dll,bin\\\\Win64_Shipping_Client\\\\grGraniteDX11.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Engine.dll,bin\\\\Win64_Shipping_Client\\\\Steamworks.NET.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Diamond.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.dll,bin\\\\Win64_Shipping_Client\\\\steam_api64.dll,bin\\\\Win64_Shipping_Client\\\\Mono.Cecil.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.AutoGenerated.dll,bin\\\\Win64_Shipping_Client\\\\grGraniteDX12.dll,bin\\\\Win64_Shipping_Client\\\\gsymsrv.dll,bin\\\\Win64_Shipping_Client\\\\PhysXCooking_64.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Library.dll,bin\\\\Win64_Shipping_Client\\\\grCore.dll,bin\\\\Win64_Shipping_Client\\\\StbSharp.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Localization.dll,bin\\\\Win64_Shipping_Client\\\\dbgcore.dll,bin\\\\Win64_Shipping_Client\\\\symsrv.dll,bin\\\\Win64_Shipping_Client\\\\MonoPosixHelper.dll,bin\\\\Win64_Shipping_Client\\\\System.Numerics.Vectors.dll,bin\\\\Win64_Shipping_Client\\\\Launcher.Native.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.SaveSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.SteamWorkshop.exe,bin\\\\Win64_Shipping_Client\\\\Bannerlord.Native.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.Multiplayer.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.Singleplayer.exe,bin\\\\Win64_Shipping_Client\\\\Bannerlord.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.exe,bin\\\\Win64_Shipping_Client\\\\amd_ags_x64.dll,bin\\\\Win64_Shipping_Client\\\\fmod_output_controller.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PSAI.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.Library.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.CodeGenerator.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.TwoDimension.Standalone.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.TwoDimension.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.dll,bin\\\\Win64_Shipping_Client\\\\System.Management.dll,bin\\\\Win64_Shipping_Client\\\\PhysXFoundation_64.dll,bin\\\\Win64_Shipping_Client\\\\jose-jwt.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.DotNet.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Core.ViewModelCollection.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.ExtraWidgets.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Network.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.InputSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.PrefabSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ObjectSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PlatformService.Epic.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.Data.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.DotNet.AutoGenerated.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PlatformService.GOG.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PlatformService.Steam.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PlatformService.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.LinQuick.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.PlayerServices.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Engine.GauntletUI.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ModuleManager.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.GauntletUI.CodeGenerator.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ServiceDiscovery.Client.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ScreenSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ScreenSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.AchievementSystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.GauntletUI.TooltipExtensions.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.AccessProvider.Steam.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Starter.Library.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.AccessProvider.Epic.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.AccessProvider.GOG.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.SaveSystem.CodeGenerator.exe,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.ActivitySystem.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.AccessProvider.GDK.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.Diamond.AccessProvider.Test.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Helpers.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.Steam.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Multiplayer.Test.dll,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.NavigationSystem.dll,bin\\\\Win64_Shipping_Client\\\\imgui.ini,bin\\\\Win64_Shipping_Client\\\\steam_appid.txt,bin\\\\Win64_Shipping_Client\\\\Version.xml,bin\\\\Win64_Shipping_Client\\\\TaleWorlds.MountAndBlade.Launcher.exe.config"',
            "RootBuilder\\hash": "true",
            "RootBuilder\\migrated": "true",
            "RootBuilder\\backup": "true",
            "RootBuilder\\cache": "true",
            "RootBuilder\\usvfspriority": "3",
            "RootBuilder\\linkpriority": "2",
            "RootBuilder\\copypriority": "1",
            "RootBuilder\\autobuild": "true",
            "RootBuilder\\installer": "false",
            "RootBuilder\\linkextensions": '"dll,exe"',
            "RootBuilder\\linkmode": "false",
            "RootBuilder\\linkonlymode": "false",
            "RootBuilder\\loglevel": "1",
            "RootBuilder\\priority": "110",
            "RootBuilder\\redirect": "true",
            "RootBuilder\\usvfsmode": "false"
        }

        # Remove any existing RootBuilder settings (both \ and /) to avoid duplicates
        for key in list(config["Plugins"]):
            if key.startswith("RootBuilder\\") or key.startswith("RootBuilder/"):
                del config["Plugins"][key]

        # Write new settings to [Plugins] section
        for key, val in values.items():
            config["Plugins"][key] = val

        # Save the INI file
        with ini_path.open("w", encoding="utf-8") as f:
            config.write(f)

        QMessageBox.information(
            None,
            "Root Builder Configured",
            "Root Builder settings have been overwritten in ModOrganizer.ini under [Plugins]."
        )


def createPlugin() -> mobase.IPlugin:
    return RootBuilderConfigurator()